//===================================================================
// COPYRIGHT Atos 2023-07-28
//===================================================================
// AtosAddin.cpp
// Header definition of class AtosAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023-07-28 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtosAddin_H
#define ExportedByAtosAddin_H
#if defined(__AtosAddin)
# define ExportedByAtosAddin   DSYExport
#else // __AtosAddin
# define ExportedByAtosAddin   DSYImport
#endif  // __AtosAddin
#include "DSYExport.h"
#endif //ExportedByAtosAddin_H

