//===================================================================
// COPYRIGHT Atos 2023-07-27
//===================================================================
// AtosUI.cpp
// Header definition of class AtosUI
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023-07-27 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtosUI_H
#define ExportedByAtosUI_H
#if defined(__AtosUI)
# define ExportedByAtosUI   DSYExport
#else // __AtosUI
# define ExportedByAtosUI   DSYImport
#endif  // __AtosUI
#include "DSYExport.h"
#endif //ExportedByAtosUI_H

