// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module AtosUI
#======================================================================
#  2023-07-27 Creation: Code generated by the 3DS wizard
#======================================================================
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = JS0GROUP \ 
			   DI0PANV2  \
			   JS0FM \ 
			   CATObjectModelerBase \ 
            CATDialogEngine  \ 
            CATAfrFoundation \
            CATPLMComponentInterfaces \
            CATVisItf \
            ObjectModelerSystem \
            CATProductStructureUseItf \
            CATPartUseItf \
            CATImmVPMInterfaces \
			SceneGraphManager \
			VPMEditorInterfaces \
			CATSysTS \
			CATAfrItf \
			CATPLMIdentificationAccess \
			KnowledgeItf \
			CATStrUseItf \
			CATWeightEquivalentUseItf \
			CATMathematics \
			CATTTRSUseItf\
			CATObjectModelerNavigator\
			CATMecModUseItf\
			CATMecModLiveUseItf\
			CATGSMUseItf\
			CATGMGeometricInterfaces\
			DataCommonProtocolUse\
# END WIZARD EDITION ZONE