//===================================================================
// COPYRIGHT Atos 2023-07-27
//===================================================================
// MyAtoscmd.cpp
// Header definition of class MyAtoscmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023-07-27 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MyAtoscmd_H
#define MyAtoscmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
// Mathematics Framework
#include "CATMathPoint.h"
#include "CATCSO.h"
#include"CATIMmiMechanicalFeature.h"
#include"CATIGSMUseFactory.h"
#include"CATIGSMUseLinePtPt.h"
#include "CATIGSMTool.h"
#include"CATUnicodeString.h"
class CATBaseUnknown;
class CATIndicationAgent;
class TestAutosDlg;
class CATPathElementAgent;
class CATPathElement;
class CATUnicodeString;
class CATIGSMUseFactory;
//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class MyAtoscmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( MyAtoscmd, CATStateCommand )

public:
MyAtoscmd();
virtual ~MyAtoscmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();
CATBoolean OnFPPointSelection(void* data);
CATBoolean OnSPPointSelection(void* data);
HRESULT LookingForAnyTypeOfBody(CATIGSMTool** piGsmtool);
//CATIGSMUseLinePtPt_var CreateLine(CATIMmiMechanicalFeature_var spFPMechFeat1, CATIMmiMechanicalFeature_var spSPMechFeat2);
//CATBoolean  CreateLine(void* iUsefulData);
/**
* Action associated to state transitions.
*/
/*virtual CATBoolean  ActionOne(void* data);*/

private:
	

	CATBoolean OnOK(void* data);
	TestAutosDlg* pDlg;
	CATStatusChangeRC Cancel(CATCommand* iCommand, CATNotification* iNotif);
	
	CATPathElementAgent* pSelectAgent;
	CATBaseUnknown* pSelectedElement;
	CATDialogAgent* pOKAgent;
	CATDialogAgent* pCancelAgent;
	CATPathElementAgent* _pFPSelectAgent;
	CATPathElementAgent* _pSPSelectAgent;
	CATPathElementAgent* _daPathElement;
	
	CATBaseUnknown* _pUIActiveObject;
	CATBaseUnknown* _pContainer;
	CATCSO* _pCSO;
	CATIMmiMechanicalFeature_var spFPMechFeat1;
	CATIMmiMechanicalFeature_var spSPMechFeat2;
	
	
	CATFrmEditor* _editor;
	CATPathElementAgent* _PointSelectionAgent;
	
};

//----------------------------------------------------------------------

#endif
