//===================================================================
// COPYRIGHT Atos 2023-07-28
//===================================================================
// MyAtosAddin.cpp
// Header definition of class MyAtosAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023-07-28 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MyAtosAddin.h"
#include "CATCreateWorkshop.h"
//#include "CATCommandHeader.h"
#include "CATAfrCommandHeader.h"
#include "CATBaseUnknown.h"
#include "CATFrmContext.h"
#include "CATApplicationFrame.h"
#include "CATIShapeDesignWorkshopAddin.h"
#include <iostream>
//MacDeclareHeader(MyAtosAddinHeader);

CATImplementClass(MyAtosAddin, DataExtension, CATIShapeDesignWorkshopAddin, MyAtosAddin);

CATImplementBOA(CATIShapeDesignWorkshopAddin, MyAtosAddin);

#include "TIE_CATIShapeDesignWorkshopAddin.h"
TIE_CATIShapeDesignWorkshopAddin(MyAtosAddin);


//-----------------------------------------------------------------------------
// MyAtosAddin : constructor
//-----------------------------------------------------------------------------
MyAtosAddin::MyAtosAddin():CATIShapeDesignWorkshopAddin()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// MyAtosAddin : destructor
//-----------------------------------------------------------------------------
MyAtosAddin::~MyAtosAddin()
{
//
// TODO: Place code here.
//
}
void MyAtosAddin::CreateCommands()
{
	
//new MyAtosAddinHeader("BasicCmd", "AtosUI", "MyAtosCmd", (void*)NULL);
	//CATBaseUnknown* _pDump = NULL;
	//_pDump = CATAfrCommandHeader::CATCreateCommandHeader("BasicCmd", "AtosUI", "MyAtosCmd", (void*)NULL, "BasicCmd", CATFrmAvailable);
//CATBaseUnknown* _pDump = NULL;
 CATAfrCommandHeader::CATCreateCommandHeader("BasicCmdAtos", "AtosUI", "MyAtoscmd", (void*)NULL, "BasicCmdAtosHdr", CATFrmAvailable);


}
CATCmdContainer* MyAtosAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pMyToolbar, MyToolbar);
	NewAccess(CATCmdStarter, pBasicCmd, BasicCmd);
	SetAccessCommand(pBasicCmd, "BasicCmdAtos");
	SetAccessChild(pMyToolbar, pBasicCmd);
	AddToolbarView(pMyToolbar, 1, Bottom);
	return pMyToolbar;
	if (pMyToolbar == NULL)
	{
		std::cout << "error";
	}
	}









