
//===================================================================
// COPYRIGHT Atos 2023-07-28
//===================================================================
// MyAtosAddin.cpp
// Header definition of class MyAtosAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023-07-28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MyAtosAddin_H
#define MyAtosAddin_H

#include "CATBaseUnknown.h"
#include "CATIShapeDesignWorkshopAddin.h"
//-----------------------------------------------------------------------
class CATCmdContainer;
class MyAtosAddin : public CATIShapeDesignWorkshopAddin

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MyAtosAddin ();
virtual ~MyAtosAddin ();

//
// TODO: Add your methods for this class here.
//
void CreateCommands();
CATCmdContainer* CreateToolbars();


private:
// Copy constructor and equal operator
// -----------------------------------
MyAtosAddin (MyAtosAddin &);
MyAtosAddin& operator=(MyAtosAddin&);
};

//-----------------------------------------------------------------------

#endif

